### ISSUE TITLE
Migrations dependencies are not respected

### ISSUE THREAD

**Issue by mariano-dagostino** [Gizra/drupal-starter#266]
Dependencies defined in .yml files like this:

```
dependencies:
  enforced:
    module:
      - server_migrate
    migration:
      - user
      - tags
      - media_image
```

Does not seems respected. The right syntax seems to be:

```
migration_dependencies:
  required:
      - user
      - tags
      - media_image
  optional: []
```
